# Generated by Django 3.2.5 on 2021-09-17 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCharitySocialNetwork', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emotioncomment',
            name='image',
        ),
        migrations.RemoveField(
            model_name='emotionpost',
            name='image',
        ),
        migrations.AlterField(
            model_name='newspost',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='AppCharitySocialNetwork.newscategory'),
        ),
        migrations.AlterUniqueTogether(
            name='newspost',
            unique_together={('title', 'user')},
        ),
    ]
