# Generated by Django 3.2.5 on 2021-09-17 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCharitySocialNetwork', '0002_auto_20210917_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotioncomment',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emotions_comment', related_query_name='emotions_comment', to='AppCharitySocialNetwork.comment', verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='emotioncomment',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppCharitySocialNetwork.emotiontype'),
        ),
        migrations.AlterField(
            model_name='emotionpost',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppCharitySocialNetwork.emotiontype'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Thông báo hệ thông'), (1, 'Thông báo người dùng'), (2, 'Thông báo bài viết mới'), (3, 'Thông báo có bài viết đấu giá'), (4, 'Report')], default=0, help_text='Chọn loại thông báo'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notificationuser',
            name='notification',
            field=models.OneToOneField(help_text='Chọn thông báo cho người dùng', on_delete=django.db.models.deletion.CASCADE, related_name='users', related_query_name='users', to='AppCharitySocialNetwork.notification'),
        ),
        migrations.AlterField(
            model_name='notificationuser',
            name='user',
            field=models.ForeignKey(help_text='Chọn người dùng cần thông báo', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
