# Generated by Django 3.2.5 on 2021-07-29 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCharitySocialNetwork', '0002_auto_20210728_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='newscategory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='newspost',
            options={},
        ),
        migrations.RenameField(
            model_name='newspost',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='result',
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='report',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterUniqueTogether(
            name='newscategory',
            unique_together={('name',)},
        ),
        migrations.AlterUniqueTogether(
            name='newspost',
            unique_together={('title',)},
        ),
        migrations.RemoveField(
            model_name='newspost',
            name='tile',
        ),
        migrations.CreateModel(
            name='EmotionPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='author', to=settings.AUTH_USER_MODEL)),
                ('emotion_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='emotion_type', to='AppCharitySocialNetwork.emotiontype')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCharitySocialNetwork.newspost')),
            ],
            options={
                'ordering': ['emotion_type', 'post'],
                'unique_together': {('author', 'post')},
            },
        ),
        migrations.CreateModel(
            name='EmotionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='author', to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCharitySocialNetwork.comment')),
                ('emotion_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='emotion_type', to='AppCharitySocialNetwork.emotiontype')),
            ],
            options={
                'ordering': ['emotion_type', 'comment'],
                'unique_together': {('author', 'comment')},
            },
        ),
    ]
