# Generated by Django 3.2.5 on 2021-07-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCharitySocialNetwork', '0003_auto_20210730_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='price_received',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='price_start',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='historyauction',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
    ]
