# Generated by Django 3.2.5 on 2021-07-29 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCharitySocialNetwork', '0003_auto_20210729_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppCharitySocialNetwork.comment'),
        ),
    ]
