# Generated by Django 3.2.5 on 2021-09-17 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCharitySocialNetwork', '0003_auto_20210918_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationuser',
            name='notification',
            field=models.ForeignKey(help_text='Chọn thông báo cho người dùng', on_delete=django.db.models.deletion.CASCADE, related_name='users', related_query_name='users', to='AppCharitySocialNetwork.notification'),
        ),
    ]
