# Generated by Django 3.2.5 on 2021-07-31 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCharitySocialNetwork', '0004_auto_20210730_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppCharitySocialNetwork.newspost', unique=True),
        ),
    ]
