# Generated by Django 3.2.5 on 2021-09-17 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCharitySocialNetwork', '0004_alter_notificationuser_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='new',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(help_text='Chọn người dùng cần thông báo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='NotificationUser',
        ),
    ]
