# Generated by Django 3.2.5 on 2021-07-29 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCharitySocialNetwork', '0005_auto_20210729_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppCharitySocialNetwork.optionreport'),
        ),
    ]
