# Generated by Django 3.2.5 on 2021-07-31 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCharitySocialNetwork', '0005_alter_auctionitem_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auctionitem',
            options={},
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppCharitySocialNetwork.newspost'),
        ),
        migrations.AlterUniqueTogether(
            name='auctionitem',
            unique_together={('post',)},
        ),
    ]
