# Generated by Django 3.2.5 on 2021-07-29 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCharitySocialNetwork', '0006_auto_20210729_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='option',
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppCharitySocialNetwork.optionreport'),
        ),
    ]
