# Generated by Django 3.2.5 on 2021-10-04 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCharitySocialNetwork', '0006_alter_auctionitem_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='provider',
        ),
        migrations.AddField(
            model_name='transaction',
            name='auction_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppCharitySocialNetwork.auctionitem'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='buyer',
            field=models.ForeignKey(help_text='Thông tin người mua', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency_code',
            field=models.CharField(default='USD', help_text='Yêu cầu nhập mã loại tiền tệ', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='seller',
            field=models.ForeignKey(help_text='Thông tin người bán', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'INCOMPLETE'), (1, 'COMPLETED')], default=0, help_text='Trạng thái mặc định của hóa đơn là chưa hoàn thành'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order_id',
            field=models.CharField(blank=True, help_text='Có mới lưu mã hóa đơn của paypal', max_length=255, null=True),
        ),
    ]
