# Generated by Django 3.2.5 on 2021-08-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCharitySocialNetwork', '0007_auto_20210801_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='auctionitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='auctionitem',
            name='name',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='images/%y/%M/%d/'),
        ),
    ]
