# Generated by Django 3.2.5 on 2021-10-06 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCharitySocialNetwork', '0008_remove_transaction_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='auction_item',
            field=models.ForeignKey(help_text='Mã bài viết không được để trống', null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppCharitySocialNetwork.auctionitem'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='update_date',
            field=models.DateTimeField(),
        ),
    ]
