# Generated by Django 3.2.5 on 2021-08-10 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCharitySocialNetwork', '0008_auto_20210805_0353'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Report',
            new_name='ReportPost',
        ),
        migrations.AlterModelOptions(
            name='newscategory',
            options={'ordering': ['created_date']},
        ),
        migrations.AlterModelOptions(
            name='newspost',
            options={},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_parent',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_child',
            field=models.ManyToManyField(blank=True, null=True, to='AppCharitySocialNetwork.Comment'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='comments',
            field=models.ManyToManyField(null=True, related_query_name='comments', to='AppCharitySocialNetwork.Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emotioncomment',
            name='emotion_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppCharitySocialNetwork.emotiontype'),
        ),
        migrations.AlterField(
            model_name='emotionpost',
            name='emotion_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppCharitySocialNetwork.emotiontype'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='hashtag',
            field=models.ManyToManyField(blank=True, to='AppCharitySocialNetwork.Hashtag'),
        ),
        migrations.CreateModel(
            name='ReportUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('content', models.TextField()),
                ('reason', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppCharitySocialNetwork.optionreport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_report', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='reports_user',
            field=models.ManyToManyField(related_query_name='reports_user', to='AppCharitySocialNetwork.ReportUser'),
        ),
    ]
