# Generated by Django 3.2.5 on 2021-07-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCharitySocialNetwork', '0008_auto_20210730_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='fee',
        ),
        migrations.AddField(
            model_name='transaction',
            name='order_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
