# Generated by Django 3.2.5 on 2021-10-07 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCharitySocialNetwork', '0009_auto_20211007_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='auction_item',
            field=models.OneToOneField(help_text='Mã bài viết không được để trống', null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppCharitySocialNetwork.auctionitem'),
        ),
    ]
