# Generated by Django 3.2.5 on 2021-08-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCharitySocialNetwork', '0009_auto_20210810_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='reposts',
            field=models.ManyToManyField(null=True, related_query_name='reposts', to='AppCharitySocialNetwork.ReportPost'),
        ),
    ]
