# Generated by Django 3.2.5 on 2021-07-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCharitySocialNetwork', '0009_auto_20210730_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='price_received',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
