# Generated by Django 3.2.5 on 2021-07-29 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCharitySocialNetwork', '0010_alter_auctionitem_price_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction_receiver', to=settings.AUTH_USER_MODEL),
        ),
    ]
