# Generated by Django 3.2.5 on 2021-08-10 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCharitySocialNetwork', '0010_newspost_reposts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='reports_user',
        ),
    ]
