# Generated by Django 3.2.5 on 2021-08-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCharitySocialNetwork', '0011_remove_user_reports_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_child',
            field=models.ManyToManyField(blank=True, to='AppCharitySocialNetwork.Comment'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='comments',
            field=models.ManyToManyField(blank=True, related_query_name='comments', to='AppCharitySocialNetwork.Comment'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='reposts',
            field=models.ManyToManyField(blank=True, related_query_name='reposts', to='AppCharitySocialNetwork.ReportPost'),
        ),
    ]
