# Generated by Django 3.2.5 on 2021-10-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCharitySocialNetwork', '0011_remove_transaction_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'UNPAID'), (1, 'PAID'), (2, 'NOT YET SHIPPER'), (3, 'SHIPPING'), (4, 'SHIPPED'), (5, 'REFUND')], default=0),
        ),
    ]
