# Generated by Django 3.2.5 on 2021-08-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCharitySocialNetwork', '0012_auto_20210810_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspost',
            name='reposts',
        ),
        migrations.AddField(
            model_name='newspost',
            name='reports',
            field=models.ManyToManyField(blank=True, related_query_name='reports', to='AppCharitySocialNetwork.ReportPost'),
        ),
    ]
