# Generated by Django 3.2.5 on 2021-10-07 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCharitySocialNetwork', '0012_auctionitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'UNPAID'), (1, 'NOT YET SHIPPER'), (2, 'SHIPPING'), (3, 'SHIPPED'), (4, 'REFUND')], default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='auction_item',
            field=models.OneToOneField(help_text='Mã bài viết không được để trống', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction', to='AppCharitySocialNetwork.auctionitem'),
        ),
    ]
