# Generated by Django 3.2.5 on 2021-08-10 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCharitySocialNetwork', '0013_auto_20210810_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='newspost',
        ),
    ]
