# Generated by Django 3.2.5 on 2021-08-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCharitySocialNetwork', '0014_remove_comment_newspost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportpost',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
