# Generated by Django 3.2.5 on 2021-08-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCharitySocialNetwork', '0015_alter_reportpost_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='emotions',
            field=models.ManyToManyField(blank=True, related_query_name='emotions', to='AppCharitySocialNetwork.EmotionComment'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='emotions',
            field=models.ManyToManyField(blank=True, related_query_name='emotions', to='AppCharitySocialNetwork.EmotionPost'),
        ),
    ]
