# Generated by Django 3.2.5 on 2021-08-11 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCharitySocialNetwork', '0016_auto_20210812_0142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportuser',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='reportuser',
            unique_together={('user', 'user_report')},
        ),
    ]
