# Generated by Django 3.2.5 on 2021-08-11 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCharitySocialNetwork', '0017_auto_20210812_0315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportuser',
            options={'ordering': ['id']},
        ),
        migrations.AlterUniqueTogether(
            name='reportuser',
            unique_together=set(),
        ),
    ]
