# Generated by Django 3.2.5 on 2021-08-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCharitySocialNetwork', '0018_auto_20210812_0320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('new', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='notifications',
            field=models.ManyToManyField(blank=True, to='AppCharitySocialNetwork.Notification'),
        ),
    ]
